---
language: ruby
script: "bundle exec qed"
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - rbx
  - jruby
  - ree
matrix:
  allow_failures:
    - rvm: rbx
cache: bundler
env:
  - confectionless='true'

