--- !ruby/object:RDoc::RI::ClassDescription 
attributes: 
- !ruby/object:RDoc::RI::Attribute 
  comment: 
  name: local
  rw: RW
class_methods: 
- !ruby/object:RDoc::RI::MethodSummary 
  name: new
comment: 
constants: []

full_name: QED::Config
includes: []

instance_methods: []

name: Config
superclass: Object
