--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: []

full_name: QED::Script#apply_environment
is_singleton: false
name: apply_environment
params: ()
visibility: public
