--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Require requirement file (from -e option.
full_name: QED::Command#require_environment
is_singleton: false
name: require_environment
params: ()
visibility: public
